<?php
/*
Plugin Name: پیامک زمان دار فراز اس‌‌ام‌‌اس
Plugin URI: https://farazsms.com/
Description: با این افزونه شما می توانید برای محصوولات ووکامرس یا فیلدهای gravity form پیامک زماندار بفرستید
Version: 3.8.4
Author: FarazSMS
Author URI: https://farazsms.com/
Text Domain: fwss
Generated By: http://ensuredomains.com
*/

if ( ! defined( 'WPINC' ) ) {
	die;
}

require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
